apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-internal-frontend
  description: "testing internal frontend "
  annotations:
    github.com/project-slug: defra-adp-sandpit/internal-frontend
    dev.azure.com/project: DEFRA-ADP
    dev.azure.com/build-definition: test-internal-frontend
    sonarqube.org/project-key: test-internal-frontend
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
    backstage.io/kubernetes-id: test-internal-frontend
  links:
    - url: https://github.com/defra-adp-sandpit/internal-frontend
      title: GitHub Repository
      icon: github
    - url: https://dev.azure.com/defragovuk/DEFRA-ADP
      title: Azure DevOps Project
      icon: project
    - url: https://sonarcloud.io/project/overview?id=test-internal-frontend
      title: SonarCloud Analysis
      icon: check
    - url: https://snyk.io/test/github/DEFRA/test-internal-frontend
      title: Snyk Analysis
      icon: policy
    - url: https://portal.azure.com/defradev.onmicrosoft.com
      title: Azure Portal - Defra Dev
      icon: cloud
    - url: https://portal.azure.com/Defra.onmicrosoft.com
      title: Azure Portal - Defra
      icon: cloud
    - url: https://test-internal-frontend.snd3.adp.defra.gov.uk/
      title: SND3
    - url: https://test-internal-frontend.dev1.adp.defra.gov.uk/
      title: DEV1
    - url: https://test-internal-frontend.tst1.adp.defra.gov.uk/
      title: TST1
    - url: https://test-internal-frontend.pre1.adp.defra.gov.uk/
      title: PRE1
spec:
  type: frontend
  lifecycle: alpha
  owner: group:default/eutd-adp-test
  system: system:default/fcp-demo-service
