{{- include "adp-helm-library.deployment" (list . "test-internal-frontend.deployment") -}}
{{- define "test-internal-frontend.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "test-internal-frontend.container") }}
{{- end -}}
